baseURL = "https://weedwizard.wtf/"
languageCode = "en-us"
title = "weed wizard"
theme = "archie"
copyright = "© Guards of Lourn"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
  mode = "toggle"
  useCDN = false

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "all posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "about"
url = "/about"
weight = 3

[[menu.main]]
name = "tags"
url = "/tags"
weight = 4
